### ISSUE TITLE
Issue with the code running on OpenVINO 2020 R4

### ISSUE THREAD

**Issue by allenwsh82** [BenedictusAryo/OpenVino_face-detection_python#1]
Hi,

I have difficulties running the code for OpenVINO2020 R4 as it cannot find this files:
WINDOWS_CPU_PLUGIN = r"C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\inference_engine\bin\intel64\Release\cpu_extension_avx2.dll"

Eventually in OpenVINO 2020 R4, they removed this pu_extension_avx2.dll, any idea how to solve this error?

Thanks

**Comment by BenedictusAryo** [comment]
@allenwsh82 Hi, Thanks for reaching out, 
yes you're right, now they included the extension into the IECore plugin, so no need to specify extension directly 
I just updated the code, can you test it out with : 

> python face_detection.py --device cpu

to test with webcam or

> python face_detection.py --device cpu --sample

to test with sample video

**Comment by allenwsh82** [comment]
Thank you so much!
